name: Black Code Formatter

on:
  push:
    branches:
      - '*'  # Run on all branches
  pull_request:
    branches:
      - '*'  # Run on all branches for PRs

jobs:
  black-check:
    runs-on: ubuntu-latest
    name: Check Black formatting

    steps:
    - name: Checkout code
      uses: actions/checkout@v4

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install Poetry
      uses: snok/install-poetry@v1
      with:
        version: latest
        virtualenvs-create: true
        virtualenvs-in-project: true

    - name: Cache Poetry dependencies
      uses: actions/cache@v3
      with:
        path: .venv
        key: venv-${{ runner.os }}-${{ hashFiles('**/poetry.lock') }}
        restore-keys: |
          venv-${{ runner.os }}-

    - name: Install dependencies
      run: poetry install --only=dev

    - name: Run Black check
      run: poetry run black --check --diff network_check_tool/

    - name: Run Black check on tests (if exists)
      run: |
        if [ -d "tests" ]; then
          poetry run black --check --diff tests/
        fi
      continue-on-error: false

  black-format:
    runs-on: ubuntu-latest
    name: Auto-format with Black
    needs: black-check
    if: failure() && github.event_name == 'push'

    steps:
    - name: Checkout code
      uses: actions/checkout@v4
      with:
        token: ${{ secrets.GITHUB_TOKEN }}

    - name: Set up Python
      uses: actions/setup-python@v4
      with:
        python-version: '3.10'

    - name: Install Poetry
      uses: snok/install-poetry@v1
      with:
        version: latest
        virtualenvs-create: true
        virtualenvs-in-project: true

    - name: Install dependencies
      run: poetry install --only=dev

    - name: Run Black formatter
      run: |
        poetry run black network_check_tool/
        if [ -d "tests" ]; then
          poetry run black tests/
        fi

    - name: Commit changes
      run: |
        git config --local user.email "action@github.com"
        git config --local user.name "GitHub Action"
        git add -A
        git diff --staged --quiet || git commit -m "Auto-format code with Black 🖤

        🤖 Generated with [Claude Code](https://claude.ai/code)

        Co-Authored-By: Claude <noreply@anthropic.com>"

    - name: Push changes
      uses: ad-m/github-push-action@master
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}
        branch: ${{ github.ref }}